"""add product name

Revision ID: 0a0b734cd579
Revises: 9592e44595ca
Create Date: 2026-06-22 11:39:35.397069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0b734cd579'
down_revision = '9592e44595ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=225), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
