"""Create announcement table

Revision ID: 1613aa37e474
Revises: 4a9734b96e07
Create Date: 2026-07-20 17:05:11.051052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1613aa37e474'
down_revision = '4a9734b96e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pinned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('popup', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.alter_column('announcement_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.create_foreign_key("fk_announcement_created_by_user", 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_constraint("fk_announcement_created_by_user", type_='foreignkey')
        batch_op.alter_column('announcement_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('created_by')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('popup')
        batch_op.drop_column('pinned')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
