"""Clean up Paystack account fields

Revision ID: 17684ca0379b
Revises: 2b34069e7cca
Create Date: 2026-07-24 13:03:17.778825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17684ca0379b'
down_revision = '2b34069e7cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bank_name')
        batch_op.drop_column('customer_code')
        batch_op.drop_column('account_name')
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('customer_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
