"""Add virtual account fields

Revision ID: 224c1470dc09
Revises: 991277be37ca
Create Date: 2026-07-03 13:43:29.550015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224c1470dc09'
down_revision = '991277be37ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('customer_code', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('customer_code')
        batch_op.drop_column('account_name')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
