"""Add Paystack virtual account fields

Revision ID: 991277be37ca
Revises: e3f05f18c43e
Create Date: 2026-07-03 11:02:02.674205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991277be37ca'
down_revision = 'e3f05f18c43e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paystack_customer_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('paystack_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('virtual_account_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('virtual_account_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('virtual_bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('virtual_account_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('paystack_dedicated_account_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('paystack_dedicated_account_id')
        batch_op.drop_column('virtual_account_reference')
        batch_op.drop_column('virtual_bank_name')
        batch_op.drop_column('virtual_account_name')
        batch_op.drop_column('virtual_account_number')
        batch_op.drop_column('paystack_customer_id')
        batch_op.drop_column('paystack_customer_code')

    # ### end Alembic commands ###
