"""add electricity transaction detail fields

Revision ID: a4bb7f909705
Revises: 0a0b734cd579
Create Date: 2026-06-22 13:08:57.453138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bb7f909705'
down_revision = '0a0b734cd579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('provider_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('provider_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('disco_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('disco_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('meter_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('meter_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('units',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('units',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('meter_type')
        batch_op.drop_column('meter_number')
        batch_op.drop_column('disco_name')
        batch_op.drop_column('disco_code')
        batch_op.drop_column('provider_message')
        batch_op.drop_column('provider_status')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
