"""Upgrade WalletTransaction model

Revision ID: d1a28214e540
Revises: 0640015aeff9
Create Date: 2026-07-09 17:28:10.107021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a28214e540'
down_revision = '0640015aeff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('performed_by', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transaction', schema=None) as batch_op:
        batch_op.drop_column('performed_by')
        batch_op.drop_column('description')
        batch_op.drop_column('source')
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###
