"""upgrade transaction model for electricity and cable tv

Revision ID: d43c5dc90cad
Revises: 8f2f0b4f248f
Create Date: 2026-06-23 11:14:25.263278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43c5dc90cad'
down_revision = '8f2f0b4f248f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cable_tv_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cable_tv_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('package_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('package_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('smartcard_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('subscription_period', sa.String(length=100), nullable=True))
        batch_op.alter_column('reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('network',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('network',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('customer_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('product_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=225),
               existing_nullable=True)
        batch_op.alter_column('reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('subscription_period')
        batch_op.drop_column('smartcard_number')
        batch_op.drop_column('package_name')
        batch_op.drop_column('package_code')
        batch_op.drop_column('cable_tv_name')
        batch_op.drop_column('cable_tv_code')
        batch_op.drop_column('provider_status')

    # ### end Alembic commands ###
