"""Add betting transaction fields

Revision ID: e3f05f18c43e
Revises: a166360dd067
Create Date: 2026-06-28 09:30:03.623981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f05f18c43e'
down_revision = 'a166360dd067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('betting_company_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('betting_company_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('betting_customer_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('betting_customer_id')
        batch_op.drop_column('betting_company_name')
        batch_op.drop_column('betting_company_code')

    # ### end Alembic commands ###
